### ISSUE TITLE
Check Code CI Performance Improvements

### ISSUE THREAD

**Issue by sergioflores-j** [sergioflores-j/ts-to-go#15]
Based on #4 and #13 

We need to have a caching mechanism in place (should also check turbo.json configuration)
Also, we need to make sure to only build/test package affected by changes done in the PR itself. To save build time.

Possible WIP solution:

```yml
name: Check Code

on:
  push:
    branches: ["main"]
  pull_request:

# TODO: determine the affected range of commits (something like https://github.com/nrwl/nx-set-shas)
env: 
  FROM_COMMIT: "[HEAD^1]"
  TO_COMMIT: ${{ github.event.number || github.ref_name }}

jobs:
  check_code:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that turbo has a base to compare against.
          fetch-depth: 0

      - uses: actions/checkout@v3
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          # We need to fetch all branches and commits so that turbo has a base to compare against.
          fetch-depth: 0

      # - uses: volta-cli/action@v4
      #   with:
      #     package-json-path: '${{ github.workspace }}/package.json'
  
      # - name: Use the package manager cache if available
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      # TODO: use parallel jobs
      - run: npm run build-affected
      - run: npm run lint-affected
      - run: npm run test-affected

```
